services:
  - name: youtube-summarizer
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
